[package]
description = "CosmWasm integration testing for Persistence"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "persistence-test-tube"
repository = "https://github.com/persistenceOne/test-tube"
version = "0.2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = ["persistenceCore", "test_artifacts"]

[dependencies]
base64 = "0.13.0"
cosmrs = {version = "0.15.0", features = ["cosmwasm"]}
cosmwasm-std = "1.4.0"
persistence-std = "0.1.6"
prost = "0.12.0"
serde = "1.0.144"
serde_json = "1.0.85"
test-tube-x = {version = "0.2.0", path = "../test-tube-x", features = ["module-wrappers"]}
thiserror = "1.0.34"

[build-dependencies]
bindgen = "0.60.1"

[dev-dependencies]
cw1-whitelist = "0.15.0"
rayon = "1.5.3"
