[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "test-tube"
repository = "https://github.com/osmosis-labs/test-tube"
version = "0.1.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
cosmrs = {version = "0.15.0", features = ["cosmwasm", "rpc"]}
cosmwasm-std = {version = "1.4.0", features = ["stargate"]}
persistence-std = {version = "0.1.8", optional = true}
prost = "0.12.0"
serde = "1.0.144"
serde_json = "1.0.85"
thiserror = "1.0.34"

[dev-dependencies]
cw1-whitelist = "0.15.0"
rayon = "1.5.3"

[features]
default = []

module-wrappers = ["bank", "wasm"]

bank = ["persistence-std"]
wasm = ["persistence-std"]
